FROM node:22 AS base

ENV NODE_ENV=development
ENV NUXT_BUILD_DIR=.nuxt-docker

WORKDIR /app

# Build
FROM base AS build

COPY --link package.json yarn.lock .yarnrc.yml ./

RUN corepack enable
RUN yarn

# Run
FROM base

COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/.yarn /app/.yarn
COPY --from=build /app/.nuxt /app/.nuxt
COPY --from=build /app/.yarnrc.yml /app/.yarnrc.yml
COPY --from=build /app/package.json /app/package.json
COPY --from=build /app/yarn.lock /app/yarn.lock

RUN corepack enable

RUN chmod +x node_modules/.bin/nuxt

CMD [ "yarn", "dev" ]
